// See https://aka.ms/new-console-template for more information
Console.WriteLine("Helo, C# Academy. One more modification!");
Console.WriteLine("Helo, C# Academy. One more modification!");
Console.WriteLine("Helo, C# Academy. One more modification!");
Console.WriteLine("Helo, C# Academy. One more modification!");
Console.WriteLine("Helo, C# Academy. One more modification!");
Console.WriteLine("Helo, C# Academy. One more modification!");
Console.WriteLine("Helo, C# Academy. One more modification!");
Console.WriteLine("Helo, C# Academy. One more modification!");
